//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziggeo.Xamarin.NetStandard.Demo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ziggeo.Xamarin.NetStandard.Demo.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about_header {
            get {
                return ResourceManager.GetString("about_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            \nVisit &lt;a href=https://github.com/Ziggeo/Android-Client-SDK&gt;GitHub&lt;/a&gt; if you want to star us or just
        ///            to see the sources
        ///            \n\nYou might also want to take a look at other sections.
        ///            \n\nLearn:
        ///            \n- &lt;a href=https://ziggeo.com/quickstart&gt;Quick start&lt;/a&gt;
        ///            \n- &lt;a href=https://ziggeo.com/screencasts&gt;Screencasts&lt;/a&gt;
        ///            \n- &lt;a href=https://ziggeo.com/webinars&gt;Webinars&lt;/a&gt;
        ///            \n\nReference:
        ///            \n- &lt;a href=https: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_text {
            get {
                return ResourceManager.GetString("about_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for trying our demo!.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziggeo demo. Xamarin.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to ziggeo.com/quickstart on your desktop or laptop and scan QR code. This will allow you to connect your desktop and mobile demo experience.
        /// </summary>
        internal static string auth_message {
            get {
                return ResourceManager.GetString("auth_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string btn_contact_us {
            get {
                return ResourceManager.GetString("btn_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string btn_scan_qr_text {
            get {
                return ResourceManager.GetString("btn_scan_qr_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file to cut.
        /// </summary>
        internal static string btn_select_file_text {
            get {
                return ResourceManager.GetString("btn_select_file_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send report.
        /// </summary>
        internal static string btn_send_report {
            get {
                return ResourceManager.GetString("btn_send_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press me to start camera recorder.
        /// </summary>
        internal static string btn_text_start_camera_recorder {
            get {
                return ResourceManager.GetString("btn_text_start_camera_recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use entered.
        /// </summary>
        internal static string btn_use_entered_text {
            get {
                return ResourceManager.GetString("btn_use_entered_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Support.
        /// </summary>
        internal static string btn_visit_support {
            get {
                return ResourceManager.GetString("btn_visit_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Clients.
        /// </summary>
        internal static string clients_header {
            get {
                return ResourceManager.GetString("clients_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon!.
        /// </summary>
        internal static string coming_soon {
            get {
                return ResourceManager.GetString("coming_soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string common_confirm_message {
            get {
                return ResourceManager.GetString("common_confirm_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string common_no {
            get {
                return ResourceManager.GetString("common_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string common_yes {
            get {
                return ResourceManager.GetString("common_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string contact_header {
            get {
                return ResourceManager.GetString("contact_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a question about Ziggeo?\nWondering how you can start using Ziggeo?\nWish to get in touch
        ///            with someone to see how you can start using Ziggeo tomorrow?\nIf you are ready to start a video revolution
        ///            of your website / service / app or system, click on the Contact Us button to send us an email, or visit our
        ///            support base to find answers or ask us there.
        ///        .
        /// </summary>
        internal static string contact_message {
            get {
                return ResourceManager.GetString("contact_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay in touch.
        /// </summary>
        internal static string contact_title {
            get {
                return ResourceManager.GetString("contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video saved to: %s.
        /// </summary>
        internal static string cut_video_saved_to {
            get {
                return ResourceManager.GetString("cut_video_saved_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details_header {
            get {
                return ResourceManager.GetString("details_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application token.
        /// </summary>
        internal static string enter_manually_hint {
            get {
                return ResourceManager.GetString("enter_manually_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or enter manually.
        /// </summary>
        internal static string enter_qr_manually_text {
            get {
                return ResourceManager.GetString("enter_qr_manually_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It\&apos;s possible you\&apos;ve forgotten to allow index operation. Please, check app settings on the website.
        ///        .
        /// </summary>
        internal static string err_check_indexing {
            get {
                return ResourceManager.GetString("err_check_indexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened. Please, try again..
        /// </summary>
        internal static string err_common {
            get {
                return ResourceManager.GetString("err_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should not be empty..
        /// </summary>
        internal static string err_not_empty {
            get {
                return ResourceManager.GetString("err_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSelector: access forbidden.
        /// </summary>
        internal static string ev_fs_accessForbidden {
            get {
                return ResourceManager.GetString("ev_fs_accessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSelector: access granted.
        /// </summary>
        internal static string ev_fs_accessGranted {
            get {
                return ResourceManager.GetString("ev_fs_accessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSelector: canceled by user.
        /// </summary>
        internal static string ev_fs_canceledByUser {
            get {
                return ResourceManager.GetString("ev_fs_canceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSelector: error.
        /// </summary>
        internal static string ev_fs_error {
            get {
                return ResourceManager.GetString("ev_fs_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSelector: loaded.
        /// </summary>
        internal static string ev_fs_loaded {
            get {
                return ResourceManager.GetString("ev_fs_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSelector: upload selected.
        /// </summary>
        internal static string ev_fs_uploadSelected {
            get {
                return ResourceManager.GetString("ev_fs_uploadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: access forbidden.
        /// </summary>
        internal static string ev_pl_accessForbidden {
            get {
                return ResourceManager.GetString("ev_pl_accessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: access granted.
        /// </summary>
        internal static string ev_pl_accessGranted {
            get {
                return ResourceManager.GetString("ev_pl_accessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: canceled by user.
        /// </summary>
        internal static string ev_pl_canceledByUser {
            get {
                return ResourceManager.GetString("ev_pl_canceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: ended.
        /// </summary>
        internal static string ev_pl_ended {
            get {
                return ResourceManager.GetString("ev_pl_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: error.
        /// </summary>
        internal static string ev_pl_error {
            get {
                return ResourceManager.GetString("ev_pl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: loaded.
        /// </summary>
        internal static string ev_pl_loaded {
            get {
                return ResourceManager.GetString("ev_pl_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: paused.
        /// </summary>
        internal static string ev_pl_paused {
            get {
                return ResourceManager.GetString("ev_pl_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: playing.
        /// </summary>
        internal static string ev_pl_playing {
            get {
                return ResourceManager.GetString("ev_pl_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: ready to play.
        /// </summary>
        internal static string ev_pl_readyToPlay {
            get {
                return ResourceManager.GetString("ev_pl_readyToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: seek.
        /// </summary>
        internal static string ev_pl_seek {
            get {
                return ResourceManager.GetString("ev_pl_seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: access forbidden.
        /// </summary>
        internal static string ev_rec_accessForbidden {
            get {
                return ResourceManager.GetString("ev_rec_accessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: access granted.
        /// </summary>
        internal static string ev_rec_accessGranted {
            get {
                return ResourceManager.GetString("ev_rec_accessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: canceled by user.
        /// </summary>
        internal static string ev_rec_canceledByUser {
            get {
                return ResourceManager.GetString("ev_rec_canceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: countdown.
        /// </summary>
        internal static string ev_rec_countdown {
            get {
                return ResourceManager.GetString("ev_rec_countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: error.
        /// </summary>
        internal static string ev_rec_error {
            get {
                return ResourceManager.GetString("ev_rec_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: has camera.
        /// </summary>
        internal static string ev_rec_hasCamera {
            get {
                return ResourceManager.GetString("ev_rec_hasCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: has microphone.
        /// </summary>
        internal static string ev_rec_hasMicrophone {
            get {
                return ResourceManager.GetString("ev_rec_hasMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: loaded.
        /// </summary>
        internal static string ev_rec_loaded {
            get {
                return ResourceManager.GetString("ev_rec_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: manually submitted.
        /// </summary>
        internal static string ev_rec_manuallySubmitted {
            get {
                return ResourceManager.GetString("ev_rec_manuallySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: microphone health.
        /// </summary>
        internal static string ev_rec_microphoneHealth {
            get {
                return ResourceManager.GetString("ev_rec_microphoneHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: no camera.
        /// </summary>
        internal static string ev_rec_noCamera {
            get {
                return ResourceManager.GetString("ev_rec_noCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: no microphone.
        /// </summary>
        internal static string ev_rec_noMicrophone {
            get {
                return ResourceManager.GetString("ev_rec_noMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: ready to record.
        /// </summary>
        internal static string ev_rec_readyToRecord {
            get {
                return ResourceManager.GetString("ev_rec_readyToRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: recording progress.
        /// </summary>
        internal static string ev_rec_recordingProgress {
            get {
                return ResourceManager.GetString("ev_rec_recordingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: recording started.
        /// </summary>
        internal static string ev_rec_recordingStarted {
            get {
                return ResourceManager.GetString("ev_rec_recordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording stopped.
        /// </summary>
        internal static string ev_rec_recordingStopped {
            get {
                return ResourceManager.GetString("ev_rec_recordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: streaming started.
        /// </summary>
        internal static string ev_rec_streamingStarted {
            get {
                return ResourceManager.GetString("ev_rec_streamingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder: streaming stopped.
        /// </summary>
        internal static string ev_rec_streamingStopped {
            get {
                return ResourceManager.GetString("ev_rec_streamingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: error.
        /// </summary>
        internal static string ev_upl_error {
            get {
                return ResourceManager.GetString("ev_upl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: processed.
        /// </summary>
        internal static string ev_upl_processed {
            get {
                return ResourceManager.GetString("ev_upl_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: processing.
        /// </summary>
        internal static string ev_upl_processing {
            get {
                return ResourceManager.GetString("ev_upl_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: uploaded.
        /// </summary>
        internal static string ev_upl_uploaded {
            get {
                return ResourceManager.GetString("ev_upl_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: uploading started.
        /// </summary>
        internal static string ev_upl_uploadingStarted {
            get {
                return ResourceManager.GetString("ev_upl_uploadingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: upload progress.
        /// </summary>
        internal static string ev_upl_uploadProgress {
            get {
                return ResourceManager.GetString("ev_upl_uploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: verified.
        /// </summary>
        internal static string ev_upl_verified {
            get {
                return ResourceManager.GetString("ev_upl_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description for the recording (optional).
        /// </summary>
        internal static string hint_description {
            get {
                return ResourceManager.GetString("hint_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start delay (seconds).
        /// </summary>
        internal static string hint_start_delay {
            get {
                return ResourceManager.GetString("hint_start_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for the recording (optional).
        /// </summary>
        internal static string hint_title {
            get {
                return ResourceManager.GetString("hint_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token or key.
        /// </summary>
        internal static string hint_token_or_key {
            get {
                return ResourceManager.GetString("hint_token_or_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string item_about {
            get {
                return ResourceManager.GetString("item_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top clients.
        /// </summary>
        internal static string item_clients {
            get {
                return ResourceManager.GetString("item_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string item_contact {
            get {
                return ResourceManager.GetString("item_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string item_log {
            get {
                return ResourceManager.GetString("item_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        internal static string item_recordings {
            get {
                return ResourceManager.GetString("item_recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available SDKs.
        /// </summary>
        internal static string item_sdks {
            get {
                return ResourceManager.GetString("item_sdks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string item_settings {
            get {
                return ResourceManager.GetString("item_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Editor.
        /// </summary>
        internal static string item_video_editor {
            get {
                return ResourceManager.GetString("item_video_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string log_header {
            get {
                return ResourceManager.GetString("log_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app need write permission to save log info..
        /// </summary>
        internal static string log_write_permission_rationale {
            get {
                return ResourceManager.GetString("log_write_permission_rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string logout_message {
            get {
                return ResourceManager.GetString("logout_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no logs..
        /// </summary>
        internal static string message_log_empty {
            get {
                return ResourceManager.GetString("message_log_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no recordings.\nPress plus button to add some..
        /// </summary>
        internal static string message_recordings_list_empty {
            get {
                return ResourceManager.GetString("message_recordings_list_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok_ {
            get {
                return ResourceManager.GetString("ok ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app needs access to read files..
        /// </summary>
        internal static string read_storage_permission_message {
            get {
                return ResourceManager.GetString("read_storage_permission_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        internal static string recordings_header {
            get {
                return ResourceManager.GetString("recordings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available SDKs.
        /// </summary>
        internal static string sdks_header {
            get {
                return ResourceManager.GetString("sdks_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_header {
            get {
                return ResourceManager.GetString("settings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string successfully_saved_message {
            get {
                return ResourceManager.GetString("successfully_saved_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application token:.
        /// </summary>
        internal static string title_app_token {
            get {
                return ResourceManager.GetString("title_app_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or use scanner.
        /// </summary>
        internal static string use_scanner_text {
            get {
                return ResourceManager.GetString("use_scanner_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video.
        /// </summary>
        internal static string video_chooser_title {
            get {
                return ResourceManager.GetString("video_chooser_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video editor.
        /// </summary>
        internal static string video_editor_header {
            get {
                return ResourceManager.GetString("video_editor_header", resourceCulture);
            }
        }
    }
}
