//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziggeo.Xamarin.NetStandard.Demo {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ziggeo.Xamarin.NetStandard.Demo.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        internal static string ok_ {
            get {
                return ResourceManager.GetString("ok ", resourceCulture);
            }
        }
        
        internal static string common_yes {
            get {
                return ResourceManager.GetString("common_yes", resourceCulture);
            }
        }
        
        internal static string common_no {
            get {
                return ResourceManager.GetString("common_no", resourceCulture);
            }
        }
        
        internal static string coming_soon {
            get {
                return ResourceManager.GetString("coming_soon", resourceCulture);
            }
        }
        
        internal static string blur_settings {
            get {
                return ResourceManager.GetString("blur_settings", resourceCulture);
            }
        }
        
        internal static string save_settings {
            get {
                return ResourceManager.GetString("save_settings", resourceCulture);
            }
        }
        
        internal static string common_confirm_message {
            get {
                return ResourceManager.GetString("common_confirm_message", resourceCulture);
            }
        }
        
        internal static string err_common {
            get {
                return ResourceManager.GetString("err_common", resourceCulture);
            }
        }
        
        internal static string err_not_empty {
            get {
                return ResourceManager.GetString("err_not_empty", resourceCulture);
            }
        }
        
        internal static string auth_message {
            get {
                return ResourceManager.GetString("auth_message", resourceCulture);
            }
        }
        
        internal static string btn_scan_qr_text {
            get {
                return ResourceManager.GetString("btn_scan_qr_text", resourceCulture);
            }
        }
        
        internal static string btn_use_entered_text {
            get {
                return ResourceManager.GetString("btn_use_entered_text", resourceCulture);
            }
        }
        
        internal static string enter_qr_manually_text {
            get {
                return ResourceManager.GetString("enter_qr_manually_text", resourceCulture);
            }
        }
        
        internal static string enter_manually_hint {
            get {
                return ResourceManager.GetString("enter_manually_hint", resourceCulture);
            }
        }
        
        internal static string use_scanner_text {
            get {
                return ResourceManager.GetString("use_scanner_text", resourceCulture);
            }
        }
        
        internal static string title_app_token {
            get {
                return ResourceManager.GetString("title_app_token", resourceCulture);
            }
        }
        
        internal static string item_recordings {
            get {
                return ResourceManager.GetString("item_recordings", resourceCulture);
            }
        }
        
        internal static string item_settings {
            get {
                return ResourceManager.GetString("item_settings", resourceCulture);
            }
        }
        
        internal static string item_sdks {
            get {
                return ResourceManager.GetString("item_sdks", resourceCulture);
            }
        }
        
        internal static string item_clients {
            get {
                return ResourceManager.GetString("item_clients", resourceCulture);
            }
        }
        
        internal static string item_contact {
            get {
                return ResourceManager.GetString("item_contact", resourceCulture);
            }
        }
        
        internal static string item_about {
            get {
                return ResourceManager.GetString("item_about", resourceCulture);
            }
        }
        
        internal static string item_log {
            get {
                return ResourceManager.GetString("item_log", resourceCulture);
            }
        }
        
        internal static string item_video_editor {
            get {
                return ResourceManager.GetString("item_video_editor", resourceCulture);
            }
        }
        
        internal static string logout_message {
            get {
                return ResourceManager.GetString("logout_message", resourceCulture);
            }
        }
        
        internal static string recordings_header {
            get {
                return ResourceManager.GetString("recordings_header", resourceCulture);
            }
        }
        
        internal static string err_check_indexing {
            get {
                return ResourceManager.GetString("err_check_indexing", resourceCulture);
            }
        }
        
        internal static string message_recordings_list_empty {
            get {
                return ResourceManager.GetString("message_recordings_list_empty", resourceCulture);
            }
        }
        
        internal static string settings_header {
            get {
                return ResourceManager.GetString("settings_header", resourceCulture);
            }
        }
        
        internal static string hint_start_delay {
            get {
                return ResourceManager.GetString("hint_start_delay", resourceCulture);
            }
        }
        
        internal static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        internal static string successfully_saved_message {
            get {
                return ResourceManager.GetString("successfully_saved_message", resourceCulture);
            }
        }
        
        internal static string log_header {
            get {
                return ResourceManager.GetString("log_header", resourceCulture);
            }
        }
        
        internal static string message_log_empty {
            get {
                return ResourceManager.GetString("message_log_empty", resourceCulture);
            }
        }
        
        internal static string sdks_header {
            get {
                return ResourceManager.GetString("sdks_header", resourceCulture);
            }
        }
        
        internal static string clients_header {
            get {
                return ResourceManager.GetString("clients_header", resourceCulture);
            }
        }
        
        internal static string btn_send_report {
            get {
                return ResourceManager.GetString("btn_send_report", resourceCulture);
            }
        }
        
        internal static string log_write_permission_rationale {
            get {
                return ResourceManager.GetString("log_write_permission_rationale", resourceCulture);
            }
        }
        
        internal static string contact_header {
            get {
                return ResourceManager.GetString("contact_header", resourceCulture);
            }
        }
        
        internal static string contact_title {
            get {
                return ResourceManager.GetString("contact_title", resourceCulture);
            }
        }
        
        internal static string contact_message {
            get {
                return ResourceManager.GetString("contact_message", resourceCulture);
            }
        }
        
        internal static string btn_contact_us {
            get {
                return ResourceManager.GetString("btn_contact_us", resourceCulture);
            }
        }
        
        internal static string btn_visit_support {
            get {
                return ResourceManager.GetString("btn_visit_support", resourceCulture);
            }
        }
        
        internal static string details_header {
            get {
                return ResourceManager.GetString("details_header", resourceCulture);
            }
        }
        
        internal static string hint_token_or_key {
            get {
                return ResourceManager.GetString("hint_token_or_key", resourceCulture);
            }
        }
        
        internal static string hint_title {
            get {
                return ResourceManager.GetString("hint_title", resourceCulture);
            }
        }
        
        internal static string hint_description {
            get {
                return ResourceManager.GetString("hint_description", resourceCulture);
            }
        }
        
        internal static string about_header {
            get {
                return ResourceManager.GetString("about_header", resourceCulture);
            }
        }
        
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        internal static string video_editor_header {
            get {
                return ResourceManager.GetString("video_editor_header", resourceCulture);
            }
        }
        
        internal static string btn_select_file_text {
            get {
                return ResourceManager.GetString("btn_select_file_text", resourceCulture);
            }
        }
        
        internal static string read_storage_permission_message {
            get {
                return ResourceManager.GetString("read_storage_permission_message", resourceCulture);
            }
        }
        
        internal static string cut_video_saved_to {
            get {
                return ResourceManager.GetString("cut_video_saved_to", resourceCulture);
            }
        }
        
        internal static string video_chooser_title {
            get {
                return ResourceManager.GetString("video_chooser_title", resourceCulture);
            }
        }
        
        internal static string btn_text_start_camera_recorder {
            get {
                return ResourceManager.GetString("btn_text_start_camera_recorder", resourceCulture);
            }
        }
        
        internal static string ev_rec_loaded {
            get {
                return ResourceManager.GetString("ev_rec_loaded", resourceCulture);
            }
        }
        
        internal static string ev_rec_manuallySubmitted {
            get {
                return ResourceManager.GetString("ev_rec_manuallySubmitted", resourceCulture);
            }
        }
        
        internal static string ev_rec_recordingStarted {
            get {
                return ResourceManager.GetString("ev_rec_recordingStarted", resourceCulture);
            }
        }
        
        internal static string ev_rec_recordingStopped {
            get {
                return ResourceManager.GetString("ev_rec_recordingStopped", resourceCulture);
            }
        }
        
        internal static string ev_rec_countdown {
            get {
                return ResourceManager.GetString("ev_rec_countdown", resourceCulture);
            }
        }
        
        internal static string ev_rec_recordingProgress {
            get {
                return ResourceManager.GetString("ev_rec_recordingProgress", resourceCulture);
            }
        }
        
        internal static string ev_rec_readyToRecord {
            get {
                return ResourceManager.GetString("ev_rec_readyToRecord", resourceCulture);
            }
        }
        
        internal static string ev_rec_accessForbidden {
            get {
                return ResourceManager.GetString("ev_rec_accessForbidden", resourceCulture);
            }
        }
        
        internal static string ev_rec_accessGranted {
            get {
                return ResourceManager.GetString("ev_rec_accessGranted", resourceCulture);
            }
        }
        
        internal static string ev_rec_noCamera {
            get {
                return ResourceManager.GetString("ev_rec_noCamera", resourceCulture);
            }
        }
        
        internal static string ev_rec_noMicrophone {
            get {
                return ResourceManager.GetString("ev_rec_noMicrophone", resourceCulture);
            }
        }
        
        internal static string ev_rec_hasCamera {
            get {
                return ResourceManager.GetString("ev_rec_hasCamera", resourceCulture);
            }
        }
        
        internal static string ev_rec_hasMicrophone {
            get {
                return ResourceManager.GetString("ev_rec_hasMicrophone", resourceCulture);
            }
        }
        
        internal static string ev_rec_microphoneHealth {
            get {
                return ResourceManager.GetString("ev_rec_microphoneHealth", resourceCulture);
            }
        }
        
        internal static string ev_rec_canceledByUser {
            get {
                return ResourceManager.GetString("ev_rec_canceledByUser", resourceCulture);
            }
        }
        
        internal static string ev_rec_error {
            get {
                return ResourceManager.GetString("ev_rec_error", resourceCulture);
            }
        }
        
        internal static string ev_rec_streamingStarted {
            get {
                return ResourceManager.GetString("ev_rec_streamingStarted", resourceCulture);
            }
        }
        
        internal static string ev_rec_streamingStopped {
            get {
                return ResourceManager.GetString("ev_rec_streamingStopped", resourceCulture);
            }
        }
        
        internal static string ev_pl_loaded {
            get {
                return ResourceManager.GetString("ev_pl_loaded", resourceCulture);
            }
        }
        
        internal static string ev_pl_accessForbidden {
            get {
                return ResourceManager.GetString("ev_pl_accessForbidden", resourceCulture);
            }
        }
        
        internal static string ev_pl_accessGranted {
            get {
                return ResourceManager.GetString("ev_pl_accessGranted", resourceCulture);
            }
        }
        
        internal static string ev_pl_canceledByUser {
            get {
                return ResourceManager.GetString("ev_pl_canceledByUser", resourceCulture);
            }
        }
        
        internal static string ev_pl_error {
            get {
                return ResourceManager.GetString("ev_pl_error", resourceCulture);
            }
        }
        
        internal static string ev_pl_playing {
            get {
                return ResourceManager.GetString("ev_pl_playing", resourceCulture);
            }
        }
        
        internal static string ev_pl_paused {
            get {
                return ResourceManager.GetString("ev_pl_paused", resourceCulture);
            }
        }
        
        internal static string ev_pl_ended {
            get {
                return ResourceManager.GetString("ev_pl_ended", resourceCulture);
            }
        }
        
        internal static string ev_pl_seek {
            get {
                return ResourceManager.GetString("ev_pl_seek", resourceCulture);
            }
        }
        
        internal static string ev_pl_readyToPlay {
            get {
                return ResourceManager.GetString("ev_pl_readyToPlay", resourceCulture);
            }
        }
        
        internal static string ev_upl_uploaded {
            get {
                return ResourceManager.GetString("ev_upl_uploaded", resourceCulture);
            }
        }
        
        internal static string ev_upl_uploadingStarted {
            get {
                return ResourceManager.GetString("ev_upl_uploadingStarted", resourceCulture);
            }
        }
        
        internal static string ev_upl_uploadProgress {
            get {
                return ResourceManager.GetString("ev_upl_uploadProgress", resourceCulture);
            }
        }
        
        internal static string ev_upl_processing {
            get {
                return ResourceManager.GetString("ev_upl_processing", resourceCulture);
            }
        }
        
        internal static string ev_upl_processed {
            get {
                return ResourceManager.GetString("ev_upl_processed", resourceCulture);
            }
        }
        
        internal static string ev_upl_verified {
            get {
                return ResourceManager.GetString("ev_upl_verified", resourceCulture);
            }
        }
        
        internal static string ev_upl_error {
            get {
                return ResourceManager.GetString("ev_upl_error", resourceCulture);
            }
        }
        
        internal static string ev_fs_loaded {
            get {
                return ResourceManager.GetString("ev_fs_loaded", resourceCulture);
            }
        }
        
        internal static string ev_fs_accessForbidden {
            get {
                return ResourceManager.GetString("ev_fs_accessForbidden", resourceCulture);
            }
        }
        
        internal static string ev_fs_accessGranted {
            get {
                return ResourceManager.GetString("ev_fs_accessGranted", resourceCulture);
            }
        }
        
        internal static string ev_fs_canceledByUser {
            get {
                return ResourceManager.GetString("ev_fs_canceledByUser", resourceCulture);
            }
        }
        
        internal static string ev_fs_uploadSelected {
            get {
                return ResourceManager.GetString("ev_fs_uploadSelected", resourceCulture);
            }
        }
        
        internal static string ev_fs_error {
            get {
                return ResourceManager.GetString("ev_fs_error", resourceCulture);
            }
        }
    }
}
