name: Ziggeo Integration Tests
on: [ push, pull_request ]

jobs:
  drive_android:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Ziggeo.Xamarin.NetStandard.Demo.Android/AndroidTestProject2
    
    strategy:
      matrix:
        api-level: [ 23 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12.0 --android=12.0.0.3

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: nuget restore

      - name: "Run Xamarin tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          working-directory: ./Ziggeo.Xamarin.NetStandard.Demo.Android/AndroidTestProject2
          profile: Nexus 4
          script: "msbuild AndroidTestProject2.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug"

