name: Ziggeo Integration Tests
on: [ push, pull_request ]

jobs:
  drive_android:
    runs-on: macos-latest
    
    strategy:
      matrix:
        api-level: [ 23 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12.0 --android=12.0.0.3

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore
      
      #      - name: Build
      #        run: msbuild Ziggeo.Xamarin.NetStandard.Demo.Android/AndroidTestProject2/AndroidTestProject2.csproj /t:Clean /t:Build /t:PackageForAndroid /p:Configuration=Debug

      - name: Build
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          working-directory: ./Ziggeo.Xamarin.NetStandard.Demo.Android/AndroidTestProject2
          profile: Nexus 4
          script: |
            msbuild AndroidTestProject2.csproj /t:Clean /t:Build /t:PackageForAndroid /p:Configuration=Debug \
            adb shell pm list instrumentation \
            adb shell am instrument -w AndroidTestProject2.AndroidTestProject2/app.tests.TestInstrumentation
      
      #      - name: Run Xamarin tests
      #        uses: reactivecircus/android-emulator-runner@v2
      #        with:
      #          api-level: ${{ matrix.api-level }}
      #          target: ${{ matrix.target }}
      #          working-directory: ./Ziggeo.Xamarin.NetStandard.Demo.Android/AndroidTestProject2
      #          profile: Nexus 4
      #          script: " adb shell am instrument -w AndroidTestProject2.AndroidTestProject2/app.tests.TestInstrumentation "

      #      - name: "Run Xamarin tests"
      #        uses: reactivecircus/android-emulator-runner@v2
      #        with:
      #          api-level: ${{ matrix.api-level }}
      #          target: ${{ matrix.target }}
      #          working-directory: ./Ziggeo.Xamarin.NetStandard.Demo.Android/AndroidTestProject2
      #          profile: Nexus 4
      #          script: "msbuild AndroidTestProject2.csproj /t:PackageForAndroid /p:Configuration=Debug"
      
